default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5

development:
  <<: *default
  database: solidus_dev
  username: postgres
  password:
  reconnect: true

test:
  <<: *default
  database: solidus_test
  username: postgres
  password:

production:
  <<: *default
  database: solidus_prod
  username: postgres
  password:
  pool: 15
  reconnect: true

